/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author rodri
 */
public class Ejercicio2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio2.class.getName());

    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        configuracionForm();
        
        lblEjemplo.setText("Texto de ejemplo");
        
        Font fuenteInicial = new Font("Dialog", Font.PLAIN, 12);
        lblEjemplo.setFont(fuenteInicial);
        
        jComboBoxTamanios.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Obtener el tamaño seleccionado
                Integer nuevoTamanio = (Integer) jComboBoxTamanios.getSelectedItem();

                if (nuevoTamanio != null) {
                    // Obtener la fuente actual de la etiqueta para mantener el estilo (negrita, cursiva, etc.)
                    Font fuenteActual = lblEjemplo.getFont();
                    
                    // Crear una nueva fuente con el nuevo tamaño
                    Font nuevaFuente = new Font(fuenteActual.getName(), fuenteActual.getStyle(), nuevoTamanio);

                    // Aplicar la nueva fuente a la etiqueta
                    lblEjemplo.setFont(nuevaFuente);
                }
            }
        });
    }
    
    private void configuracionForm() {
        setLocationRelativeTo(null);
        
        Dimension tamMinimo = new Dimension(240,300);
        Dimension tamMaximo = new Dimension(240,300);
        
        setMinimumSize(tamMinimo);
        setMaximumSize(tamMaximo);
        
        jComboBoxTamanios.addItem(12);
        jComboBoxTamanios.addItem(14);
        jComboBoxTamanios.addItem(16);
        jComboBoxTamanios.addItem(18);
        jComboBoxTamanios.addItem(20);
        jComboBoxTamanios.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxTamanios = new javax.swing.JComboBox<>();
        lblEjemplo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(jComboBoxTamanios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, -1));

        lblEjemplo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEjemplo.setText("Texto de ejemplo");
        getContentPane().add(lblEjemplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 290, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Ejercicio2().setVisible(true));
        SwingUtilities.invokeLater(() -> new Ejercicio2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Integer> jComboBoxTamanios;
    private javax.swing.JLabel lblEjemplo;
    // End of variables declaration//GEN-END:variables
}
