/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author rodri
 */
public class Ejercicio3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio3.class.getName());
    
    private DefaultListModel<String> lista;
    
    private Map<String, String> infoLenguajes;

    /**
     * Creates new form Ejercicio3
     */
    public Ejercicio3() {
        initComponents();
        configuracionForm();
        
        jListaLenguajes.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                String seleccionado = jListaLenguajes.getSelectedValue();
                String info = "";

                if (seleccionado != null) {
                    // Usando switch/case con Strings
                    switch (seleccionado) {
                        case "Java":
                            info = "Java: Creado por Sun Microsystems (ahora Oracle). Es un lenguaje orientado a objetos, robusto y multiplataforma (Write Once, Run Anywhere).";
                            break;
                        case "Python":
                            info = "Python: Creado por Guido van Rossum. Conocido por su sintaxis clara, ideal para scripting, IA y análisis de datos.";
                            break;
                        case "C++":
                            info = "C++: Extensión de C, desarrollado por Bjarne Stroustrup. Lenguaje de propósito general, enfocado en POO y rendimiento.";
                            break;
                        case "JavaScript":
                            info = "JavaScript: Lenguaje de scripting esencial para el desarrollo web. Utilizado en front-end y back-end (Node.js). Es dinámico y multiparadigma.";
                            break;
                        case "C#":
                            info = "C#: Desarrollado por Microsoft para el framework .NET. Es orientado a objetos, usado en aplicaciones Windows, web y desarrollo de juegos (Unity).";
                            break;
                        default:
                            info = "Información no disponible para: " + seleccionado;
                            break;
                    }

                    jTextoLenguajes.setText(info);
                    jTextoLenguajes.setCaretPosition(0);
                }
            }
        });
    }
    
    private void configuracionForm() {
        setLocationRelativeTo(null);
        
        Dimension tamMinimo = new Dimension(450,340);
        Dimension tamMaximo = new Dimension(450,340);
        
        setMinimumSize(tamMinimo);
        setMaximumSize(tamMaximo);
        
        lista = new DefaultListModel<>();
        lista.addElement("Java");
        lista.addElement("Python");
        lista.addElement("C++");
        lista.addElement("JavaScript");
        lista.addElement("C#");
        
        jListaLenguajes.setModel(lista);
        
        jListaLenguajes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jTextoLenguajes.setLineWrap(true);
        jTextoLenguajes.setWrapStyleWord(true);
        jTextoLenguajes.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaLenguajes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextoLenguajes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListaLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListaLenguajes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, 111));

        jTextoLenguajes.setColumns(20);
        jTextoLenguajes.setRows(5);
        jScrollPane2.setViewportView(jTextoLenguajes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 300, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Ejercicio3().setVisible(true));
        SwingUtilities.invokeLater(() -> new Ejercicio3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListaLenguajes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextoLenguajes;
    // End of variables declaration//GEN-END:variables
}