/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author rodri
 */
public class Ejercicio4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ejercicio4.class.getName());

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
        configuracionForm();
        
        jBtnEnviar.addActionListener(new HandlerBoton());
    }
    
    private class HandlerBoton implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            String entrada = jOptMensaje.showInputDialog(jOptMensaje,"Ingrese edad: ");
            
            // 1. Intentar convertir la entrada a un número entero
            try {
                int edad = Integer.parseInt(entrada);
                
                // 2. Validar si la edad es 18 o mayor
                if (edad >= 18) {
                    jOptMensaje.showMessageDialog(
                        null, 
                        "¡Bienvenido! Tienes 18 años o más.", 
                        "Bienvenida", 
                        jOptMensaje.INFORMATION_MESSAGE
                    );
                } 
                // 3. Validar si la edad es menor a 18
                else {
                    jOptMensaje.showMessageDialog(
                        null, 
                        "Error: Debes ser mayor de 18 años para acceder.", 
                        "Error de Edad", 
                        jOptMensaje.ERROR_MESSAGE
                    );
                }
            } 
            // 4. Capturar la excepción si la conversión falla (texto no numérico o número muy grande/pequeño)
            catch (NumberFormatException error) {
                jOptMensaje.showMessageDialog(
                    null, 
                    "Error: Por favor, ingrese una edad válida (solo números enteros).", 
                    "Error de Entrada", 
                    jOptMensaje.WARNING_MESSAGE
                );
            }
        }
    }
    
    private void configuracionForm(){
        setLocationRelativeTo(null);
        
        Dimension tamMinimo = new Dimension(450,340);
        Dimension tamMaximo = new Dimension(450,340);
        
        setMinimumSize(tamMinimo);
        setMaximumSize(tamMaximo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptMensaje = new javax.swing.JOptionPane();
        jBtnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnEnviar.setText("VERIFICAR EDAD");
        getContentPane().add(jBtnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ejercicio4().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEnviar;
    private javax.swing.JOptionPane jOptMensaje;
    // End of variables declaration//GEN-END:variables
}
