/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import java.awt.Dimension;
import java.awt.Color;

/**
 *
 * @author Alumno
 */
public class frmConversor extends javax.swing.JFrame {

    /**
     * Creates new form frmConversor
     */
    public frmConversor() {
        initComponents();
        configurarForm();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
    }
    
    private void configurarForm(){
        setLocationRelativeTo(null);
        
        Dimension tamMinimo = new Dimension(330,250);
        Dimension tamMaximo = new Dimension(330,250);
        
        setMinimumSize(tamMinimo);
        setMaximumSize(tamMaximo);
        
        cmbConversion.removeAllItems();
        
        cmbConversion.addItem("C a F");
        cmbConversion.addItem("F a C");
        cmbConversion.setSelectedIndex(0);
        
        txtSalida.setEditable(false);
        
        this.getContentPane().setBackground(Color.decode("#97E6A5"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSalida = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        cmbConversion = new javax.swing.JComboBox<>();
        btnConvertir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSalida.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalida.setText("0");
        getContentPane().add(txtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));

        txtEntrada.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEntrada.setText("0");
        getContentPane().add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, -1));

        cmbConversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbConversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbConversionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbConversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        btnConvertir.setText("Convertir");
        getContentPane().add(btnConvertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 90, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbConversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbConversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbConversionActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //Métodos Getters para que el
    //controlador acceda a los componentes
    
    public JTextField getTxtEntrada() {
        return txtEntrada;
    }

    public JTextField getTxtSalida() {
        return txtSalida;
    }

    public JComboBox<String> getCmbConversion() {
        return cmbConversion;
    }

    public JButton getBtnConvertir() {
        return btnConvertir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConvertir;
    public javax.swing.JComboBox<String> cmbConversion;
    public javax.swing.JTextField txtEntrada;
    public javax.swing.JTextField txtSalida;
    // End of variables declaration//GEN-END:variables
}
