/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import javax.swing.*;
import modelo.Tarea;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author rodri
 */
public class frmGestorTareas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmGestorTareas.class.getName());
    
    private DefaultListModel<Tarea> listaModelo;

    /**
     * Creates new form frmGestorTareas
     */
    public frmGestorTareas() {
        initComponents();
        
        configurarForm();
        
        listaModelo = new DefaultListModel<>();
        jListaTareas.setModel(listaModelo);
        jListaTareas.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        jTxtTarea.setText("");
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE); 
    }
    
    private void configurarForm(){
        setLocationRelativeTo(null);
        
        Dimension tamMinimo = new Dimension(650,400);
        Dimension tamMaximo = new Dimension(650,400);
        
        setMinimumSize(tamMinimo);
        setMaximumSize(tamMaximo);
        
        lblTitulo.setText("GESTOR DE TAREAS");
        Font fuenteTitulo = new Font("Dialog", Font.BOLD + Font.ITALIC, 18);
        lblTitulo.setFont(fuenteTitulo);
        
        lblIngresar.setText("Ingrese nueva tarea:");
        
        this.getContentPane().setBackground(Color.decode("#95D2ED"));
    }
    
    // Getters para que el Controlador pueda acceder a los componentes
    public JTextField getTaskInputField() {
        return jTxtTarea;
    }

    public JButton getAddButton() {
        return jbtnAgregar;
    }

    public JButton getCompleteButton() {
        return jbtnMarcar;
    }
    
    public JList<Tarea> getTaskList() {
        return jListaTareas;
    }
    
    public DefaultListModel<Tarea> getListModel() {
        return listaModelo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaTareas = new javax.swing.JList<>();
        lblIngresar = new javax.swing.JLabel();
        jbtnMarcar = new javax.swing.JButton();
        jbtnAgregar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jTxtTarea = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(jListaTareas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 310, 280));

        lblIngresar.setText("jLabel1");
        getContentPane().add(lblIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, -1, -1));

        jbtnMarcar.setText("Marcar completada");
        getContentPane().add(jbtnMarcar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 140, -1));

        jbtnAgregar.setText("Agregar tarea");
        getContentPane().add(jbtnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 140, -1));

        lblTitulo.setText("jLabel1");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTxtTarea.setText("jTextField1");
        getContentPane().add(jTxtTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 290, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Tarea> jListaTareas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtTarea;
    private javax.swing.JButton jbtnAgregar;
    private javax.swing.JButton jbtnMarcar;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}